export const LOGUEO_USUARIO = "LOGUEO_USUARIO"
export const CAMBIO_VISTA = "CAMBIO_VISTA"
export const CERRAR_SESION = "SERRAR_SESION"
export const SETEAR_BASE_USUARIOS = "SETEAR_BASE_USUARIOS"
export const SETEAR_BASE_SUCURSALES = "SETEAR_BASE_SUCURSALES"
export const ELIMINAR_SUCURSAL = "ELIMINAR_SUCURSAL"
export const ELIMINAR_CLIENTE = "ELIMINAR_CLIENTE"
export const CLIENTE_EDITADO = "CLIENTE_EDITADO"
export const SUCURSAL_EDITADA = "SUCURSAL_EDITADA"
export const VOLVER = "VOLVER"
export const AGREGAR_CLIENTE = "AGREGAR_CLIENTE"
export const AGREGAR_SUCURSAL = "AGREGAR_SUCURSAL"
export const USUARIO_AGREGADO = "USUARIO_AGREGADO"
export const SUCURSAL_AGREGADA = "SUCURSAL_AGREGADA"



